import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/sidebar";
import SheetMobile from "@/components/sheet";
import { cn } from "@/lib/utils";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(poppins.className, "flex")}>
        <div className="hidden lg:block w-[350px]">
          <Sidebar />
        </div>
        <div className="h-full lg:hidden pt-3 px-2 flex flex-col items-center">
          <SheetMobile />
        </div>
        {children}
      </body>
    </html>
  );
}
